/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorInicioJugador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import modelo.AplicationException;
import modelo.Participante;

/**
 *
 * @author leo
 */
public class InicioJugador extends javax.swing.JFrame implements IVistaInicioJugador{

    private ControladorInicioJugador controlador;
    //private Participante participante;
    public InicioJugador(Participante p) throws AplicationException {
        initComponents();
        //participante = p;
        controlador = new ControladorInicioJugador(this, p);
        //controlador.revisaSiInicia();
        
        // Cuando Participante abandona espera
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                abandonarEspera();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFaltan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Esperando inicio del juego");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 21, 205, 20);
        getContentPane().add(lblFaltan);
        lblFaltan.setBounds(32, 53, 110, 16);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void mostrarSaludo(String nombreCompletoDelJugador) {
       this.setTitle("Bienvenido/a " + nombreCompletoDelJugador);
    }
    @Override
    public void actualizarCuantosFaltan(int cuantosJugadoresFaltan) {
        this.lblFaltan.setText("Faltan " + String.valueOf(cuantosJugadoresFaltan) + " jugadores.");
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFaltan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciarJuego(Participante participante) {
        //dispose();
        VistaJuego vj = new VistaJuego(participante);
        vj.setVisible(true);
        dispose();
    }

    @Override
    public void mostrarMensajeError(String mensaje) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void abandonarEspera() {
        int confirmed = JOptionPane.showConfirmDialog(this, 
                "Estas seguro que deseas abandonar la espera?", "Abandonar", 
                JOptionPane.YES_NO_OPTION); 

        if (confirmed == JOptionPane.YES_OPTION) 
        {                             
            controlador.abandonarEspera();
            dispose(); 
        } 
        
        
    }
    

}
