/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPanelAdmin;
import modelo.Administrador;

/**
 *
 * @author Guillermo Polachek
 */
public class InicioAdministrador extends javax.swing.JFrame implements IInicioAdministrador{

    /**
     * Creates new form InicioAdministrador
     */
    private Administrador admin;
    private ControladorPanelAdmin controlador;
    
    public InicioAdministrador(Administrador a) {
        initComponents();
        controlador = new ControladorPanelAdmin(this, a);
        admin = a;
        this.setTitle("Bienvenido " + a.getNombreCompleto());
    }
    
    @Override
    public void cargarLuz(Integer luzSistema){
        txt_value_luz.setText(""+luzSistema);
    }
    
    @Override
    public void cargarJugMesa(Integer jugMesa){
        adm_txt_jug_mesa.setText("" + jugMesa);
        jSlider_jug_mesa.setValue(jugMesa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSlider_jug_mesa = new javax.swing.JSlider();
        adm_txt_jug_mesa = new javax.swing.JLabel();
        btn_ok_cantjugmesa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_value_luz = new javax.swing.JTextField();
        btn_apuestaluz = new javax.swing.JButton();
        monitor_partidas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad de Jugadores por mesa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 87, 232, 17);

        jSlider_jug_mesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSlider_jug_mesa.setMaximum(5);
        jSlider_jug_mesa.setMinimum(2);
        jSlider_jug_mesa.setValue(4);
        jSlider_jug_mesa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_jug_mesaStateChanged(evt);
            }
        });
        getContentPane().add(jSlider_jug_mesa);
        jSlider_jug_mesa.setBounds(10, 122, 200, 16);

        adm_txt_jug_mesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adm_txt_jug_mesa.setText("jLabel2");
        getContentPane().add(adm_txt_jug_mesa);
        adm_txt_jug_mesa.setBounds(220, 118, 56, 22);

        btn_ok_cantjugmesa.setText("Confirmar");
        btn_ok_cantjugmesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_cantjugmesaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok_cantjugmesa);
        btn_ok_cantjugmesa.setBounds(290, 110, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Valor apuesta Base/Luz :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 210, 180, 17);

        txt_value_luz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_value_luz);
        txt_value_luz.setBounds(190, 230, 70, 30);

        btn_apuestaluz.setText("Confirmar");
        btn_apuestaluz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apuestaluzActionPerformed(evt);
            }
        });
        getContentPane().add(btn_apuestaluz);
        btn_apuestaluz.setBounds(290, 230, 100, 30);

        monitor_partidas.setText("Monitoreo Partidas");
        monitor_partidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitor_partidasActionPerformed(evt);
            }
        });
        getContentPane().add(monitor_partidas);
        monitor_partidas.setBounds(10, 10, 170, 40);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 20, 69, 32);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_jug_mesaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_jug_mesaStateChanged
        adm_txt_jug_mesa.setText("" + jSlider_jug_mesa.getValue());
    }//GEN-LAST:event_jSlider_jug_mesaStateChanged

    private void btn_ok_cantjugmesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_cantjugmesaActionPerformed
        Integer nuevoValor = jSlider_jug_mesa.getValue();
        controlador.cambiarCantJugMesa(nuevoValor); 
    }//GEN-LAST:event_btn_ok_cantjugmesaActionPerformed

    private void btn_apuestaluzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apuestaluzActionPerformed
        try {
            Integer nuevoValor = Integer.parseInt(txt_value_luz.getText());
            controlador.cambiarLuz(nuevoValor);
        } catch (NumberFormatException e) {
            UtilidadesVista u =new UtilidadesVista();
            u.mostrarError(this, "Debe ingresar un Número");
        }        
    }//GEN-LAST:event_btn_apuestaluzActionPerformed

    private void monitor_partidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitor_partidasActionPerformed
        iniciarMonitor();
    }//GEN-LAST:event_monitor_partidasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.logout();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void iniciarMonitor() {
        new MonitorPartidas().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adm_txt_jug_mesa;
    private javax.swing.JButton btn_apuestaluz;
    private javax.swing.JButton btn_ok_cantjugmesa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider jSlider_jug_mesa;
    private javax.swing.JButton monitor_partidas;
    private javax.swing.JTextField txt_value_luz;
    // End of variables declaration//GEN-END:variables
}
