/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorLoginJugador;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import modelo.AplicationException;
import modelo.Participante;

/**
 *
 * @author leo
 */
public class LoginJugador extends javax.swing.JFrame implements ILoginJugador{

    private ControladorLoginJugador controlador;
    
    public LoginJugador() {
        initComponents();
        controlador = new ControladorLoginJugador(this);
    }

    protected String getNombreUsuario() {
        return txtNombreUsuario.getText();
    }

    protected String getPassword() {
        return new String(txtPassword.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtNombreUsuario);
        txtNombreUsuario.setBounds(174, 86, 134, 20);

        jLabel1.setText("Usuario: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(108, 89, 62, 14);

        txtPassword.setText("jPasswordField1");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(174, 124, 134, 20);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(108, 127, 50, 14);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(174, 186, 90, 30);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        this.txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained
    
    public void login() {        
        String nombre = this.getNombreUsuario();
        String pass = this.getPassword();
        controlador.login(nombre, pass);
    }
    
    @Override
    public void mostrarError(String mensaje) {
        UtilidadesVista u =new UtilidadesVista();
        u.mostrarError(this, mensaje);
    }

    @Override
    public void ingresar(Participante p) {
        dispose();
        InicioJugador ini;
        try {
            ini = new InicioJugador(p);
            ini.setVisible(true);
        } catch (AplicationException ex) {
            Logger.getLogger(LoginJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

  
}
