/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CntlrMonitorPartidas;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import modelo.Juego;

/**
 *
 * @author Guillermo Polachek
 */
public class MonitorPartidas extends javax.swing.JFrame implements IMonitorPartidas{

    private CntlrMonitorPartidas controlador;
    
    public MonitorPartidas() {
        initComponents();
        controlador = new CntlrMonitorPartidas(this);
    }
    
    public void noHayPartidasCurso(){
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("No hay juegos en curso");
        listaPartidas.setModel(listModel);
        verPartida.setEnabled(false);
    }
    
    
    public void cargarPartidascurso(ArrayList<Juego> juegosCurso){
        verPartida.setEnabled(true);
        DefaultListModel listModel = new DefaultListModel();
        int contador = 1;
        for (Juego p : juegosCurso) {
            listModel.addElement("- Partida "+(contador++)+" > Fecha/Hora de inicio: "+p.getFechaIncio());
        }
        listaPartidas.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPartidas = new javax.swing.JList();
        verPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Partidas en curso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 130, 30);

        listaPartidas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaPartidas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 480, 130);

        verPartida.setText("Ver datos de Partida");
        verPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(verPartida);
        verPartida.setBounds(160, 230, 190, 50);

        setBounds(0, 0, 558, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void verPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPartidaActionPerformed
        if(listaPartidas.isSelectionEmpty()){
            mostrarError("Debe seleccionar una partida para ver sus datos");
        }else{
            controlador.verPartida(listaPartidas.getSelectedIndex());
        }
    }//GEN-LAST:event_verPartidaActionPerformed
    
    public void crearVisorPartida(Juego miJuego){
        new VisorPartida(miJuego).setVisible(true);
    }
            
            
    public void mostrarError(String mensaje) {
        UtilidadesVista u =new UtilidadesVista();
        u.mostrarError(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaPartidas;
    private javax.swing.JButton verPartida;
    // End of variables declaration//GEN-END:variables
}
