/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CntlrVisorPartida;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelo.Juego;

/**
 *
 * @author Polachek
 */
public class VisorPartida extends javax.swing.JFrame implements IVisorPartida{

    private CntlrVisorPartida controlador;
    
    public VisorPartida(Juego miJuego) {
        initComponents();
        controlador = new CntlrVisorPartida(this, miJuego);
        controlador.cargarDatosJuego(miJuego);
        controlador.cargarJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateJuego = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        juegoCantJug = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        juegoCantManos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        juegoTotalApostado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelJugadores = new javax.swing.JTabbedPane();
        jLabel6 = new javax.swing.JLabel();
        luzBase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ver datos de Jugadores:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 190, 280, 40);

        jLabel2.setText("Fecha/Hora de inicio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 160, 14);

        dateJuego.setText("Fecha/Hora");
        getContentPane().add(dateJuego);
        dateJuego.setBounds(210, 60, 200, 14);

        jLabel3.setText("Cantidad de jugadores en la partida:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 230, 14);

        juegoCantJug.setText("0");
        getContentPane().add(juegoCantJug);
        juegoCantJug.setBounds(270, 100, 50, 14);

        jLabel4.setText("Cantidad de manos jugadas:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 160, 14);

        juegoCantManos.setText("0");
        getContentPane().add(juegoCantManos);
        juegoCantManos.setBounds(210, 120, 50, 14);

        jLabel5.setText("Total apostado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 90, 14);

        juegoTotalApostado.setText("0");
        getContentPane().add(juegoTotalApostado);
        juegoTotalApostado.setBounds(130, 140, 30, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Datos del Juego");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 10, 150, 40);
        getContentPane().add(panelJugadores);
        panelJugadores.setBounds(20, 240, 520, 230);

        jLabel6.setText("Apuesta Base:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 80, 120, 14);

        luzBase.setText("0");
        getContentPane().add(luzBase);
        luzBase.setBounds(180, 80, 70, 14);

        setBounds(0, 0, 572, 542);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel juegoCantJug;
    private javax.swing.JLabel juegoCantManos;
    private javax.swing.JLabel juegoTotalApostado;
    private javax.swing.JLabel luzBase;
    private javax.swing.JTabbedPane panelJugadores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarDatosJuego(String FchI,int CantJug,int CantManos,int TotalApostado, int apuestaLuz) {
        dateJuego.setText(FchI);
        juegoCantJug.setText(""+CantJug);
        juegoCantManos.setText(""+CantManos);
        luzBase.setText(""+apuestaLuz);
        juegoTotalApostado.setText(""+TotalApostado);
    }
    
    @Override
    public void updateCantManos(int CantManos){
        juegoCantManos.setText(""+CantManos);
    }

    @Override
    public void cargarJugador(String nombreCompletoDelJugador, int saldoInicial, int saldoFinal, int totalApostado) {
        JPanel p=new JPanel();
        JLabel lb=new JLabel("Saldo inicial: "+saldoInicial);
        JLabel lb2=new JLabel("Saldo Final: "+saldoFinal);
        JLabel lb3=new JLabel("Total Apostado: "+totalApostado);
        p.add(lb);
        p.add(lb2);
        p.add(lb3);
        panelJugadores.addTab(nombreCompletoDelJugador, p);
    }

    @Override
    public void updateCantJug(int cantJug) {
        juegoCantJug.setText(""+cantJug);
    }

    @Override
    public void limpiTabJug() {
        panelJugadores.removeAll();
    }

    @Override
    public void updatePozo(int nuevoPozo) {
        juegoTotalApostado.setText(""+nuevoPozo);
    }
    
    @Override
    public void partidaFinalizada(){
        mostrarMensaje("La partida a finalizado");
        dispose();
    }
    
    @Override
    public void mostrarMensaje(String mensaje) {
        UtilidadesVista u = new UtilidadesVista();
        u.mostrarError(this, mensaje);
    }
}
